config/urls.py
# for midi media?

from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path, include

"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userinput.urls')),
    path('generation/', include('generation.urls')),
]


## for midi media?
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userinput/urls.py
from django.urls import path
from . import views

app_name = "userinput"
urlpatterns = [
    path("", views.index, name="index"),
    path("track/<int:id>", views.track, name="track"),
    path("trackadd/<int:id>", views.trackadd, name="trackadd"),
    path("dummy", views.dummy, name="dummy"), # not in use, sometimes used for debugging
    path("about", views.about, name="about"),
    path("instructions", views.instructions, name="instructions"),
    path("dedication", views.dedication, name="dedication"),
]

userinput/forms.py
from django.forms import ModelForm, HiddenInput, TextInput
from .models import Composition, Track

class   ProgressionForm(ModelForm):
    class   Meta:
        model = Composition
        fields = [
            "name", 
            "chord1_tonic", 
            "chord1_quality", 
            "chord1_bars",
            
            "chord2_tonic",
            "chord2_quality",
            "chord2_bars",
            
            "chord3_tonic", 
            "chord3_quality",
            "chord3_bars",
            
            "chord4_tonic",
            "chord4_quality",
            "chord4_bars",


            "chord5_tonic",
            "chord5_quality",
            "chord5_bars", 

            ]

        # widgets = {

        #     "name": TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
             

        #     ##

        #     "chord1_tonic":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }), 

        #     "chord1_quality":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }), 

        #     "chord1_bars":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     ##
            
        #     "chord2_tonic":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     "chord2_quality":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     "chord2_bars":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     ##
            
        #     "chord3_tonic":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }), 
        #     "chord3_quality":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
        #     "chord3_bars":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     ##
            
        #     "chord4_tonic":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
        #     "chord4_quality":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
        #     "chord4_bars":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     ##

        #     "chord5_tonic":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
        #     "chord5_quality":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),
        #     "chord5_bars":TextInput(attrs={
        #         'class': "",
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Name'
        #         }),

        #     ##

        # }

class   TrackForm(ModelForm):
    class   Meta:
        model = Track
        fields = [
            "trackname",

            "chord1_style",
            "chord1_denom",
            "chord1_mutators",

            "chord2_style",
            "chord2_denom",
            "chord2_mutators",

            "chord3_style",
            "chord3_denom",
            "chord3_mutators",

            "chord4_style",
            "chord4_denom",
            "chord4_mutators",

            "chord5_style",
            "chord5_denom",
            "chord5_mutators",

        ]

    #################################
    ## Addition scrap
        # widgets = {'comp': HiddenInput()}

userinput/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest

from .models import Composition, Track
from .forms import ProgressionForm, TrackForm
#==============================

def index(request):
    context = {}
    if request.method == 'POST':

        name = request.POST.get('name')

        # Chord 1
        chord1_tonic = request.POST.get('chord1_tonic')
        if chord1_tonic == "A#/Bb":
            chord1_tonic = "A#"
        elif chord1_tonic == "C#/Db":
            chord1_tonic = "C#"
        elif chord1_tonic == "D#/Eb":
            chord1_tonic = "D#"
        elif chord1_tonic == "F#/Gb":
            chord1_tonic = "F#"
        elif chord1_tonic == "G#/Ab":
            chord1_tonic = "G#"    


        chord1_quality = request.POST.get('chord1_quality')
        if request.POST.get('chord1_bars') == ("" or None):
            chord1_bars = 0
        else: chord1_bars = int(request.POST.get('chord1_bars'))

        
        # Chord 2
        chord2_tonic = request.POST.get('chord2_tonic')
        if chord2_tonic == "A#/Bb":
            chord2_tonic = "A#"
        elif chord2_tonic == "C#/Db":
            chord2_tonic = "C#"
        elif chord2_tonic == "D#/Eb":
            chord2_tonic = "D#"
        elif chord2_tonic == "F#/Gb":
            chord2_tonic = "F#"
        elif chord2_tonic == "G#/Ab":
                chord2_tonic = "G#"

        chord2_quality = request.POST.get('chord2_quality')
        if request.POST.get('chord2_bars') == ("" or None):
            chord2_bars = 0
        else: chord2_bars = int(request.POST.get('chord2_bars'))

        # Chord 3
        chord3_tonic = request.POST.get('chord3_tonic')
        if chord3_tonic == "A#/Bb":
            chord3_tonic = "A#"
        elif chord3_tonic == "C#/Db":
            chord3_tonic = "C#"
        elif chord3_tonic == "D#/Eb":
            chord3_tonic = "D#"
        elif chord3_tonic == "F#/Gb":
            chord3_tonic = "F#"
        elif chord3_tonic == "G#/Ab":
                chord3_tonic = "G#"
        chord3_quality = request.POST.get('chord3_quality')

        if request.POST.get('chord3_bars') == ("" or None):
            chord3_bars = 0
        else: chord3_bars = int(request.POST.get('chord3_bars'))

        # Chord 4
        chord4_tonic = request.POST.get('chord4_tonic')
        if chord4_tonic == "A#/Bb":
            chord4_tonic = "A#"
        elif chord4_tonic == "C#/Db":
            chord4_tonic = "C#"
        elif chord4_tonic == "D#/Eb":
            chord4_tonic = "D#"
        elif chord4_tonic == "F#/Gb":
            chord4_tonic = "F#"
        elif chord4_tonic == "G#/Ab":
                chord4_tonic = "G#"
        chord4_quality = request.POST.get('chord4_quality')
        if request.POST.get('chord4_bars') == ("" or None):
            chord4_bars = 0
        else: chord4_bars = int(request.POST.get('chord4_bars'))

        
        # Chord 5
        chord5_tonic = request.POST.get('chord5_tonic')
        if chord5_tonic == "A#/Bb":
            chord5_tonic = "A#"
        elif chord5_tonic == "C#/Db":
            chord5_tonic = "C#"
        elif chord5_tonic == "D#/Eb":
            chord5_tonic = "D#"
        elif chord5_tonic == "F#/Gb":
            chord5_tonic = "F#"
        elif chord5_tonic == "G#/Ab":
                chord5_tonic = "G#"
        chord5_quality = request.POST.get('chord5_quality')
        if request.POST.get('chord5_bars') == ("" or None):
            chord5_bars = 0
        else: chord5_bars = int(request.POST.get('chord5_bars'))

        # Create the Composition
        composition = Composition.objects.create(

            name = name,
            chord1_tonic = chord1_tonic,
            chord1_quality = chord1_quality,
            chord1_bars = chord1_bars,

            chord2_tonic = chord2_tonic,
            chord2_quality = chord2_quality,
            chord2_bars = chord2_bars,

            chord3_tonic = chord3_tonic,
            chord3_quality = chord3_quality,
            chord3_bars = chord3_bars,

            chord4_tonic = chord4_tonic,
            chord4_quality = chord4_quality,
            chord4_bars = chord4_bars,

            chord5_tonic = chord5_tonic,
            chord5_quality = chord5_quality,
            chord5_bars = chord5_bars,
            midi = None

                )
        return redirect(f"/track/{composition.id}")

    context = {}
    return render(request, "userinput/index.html", context)

def track(request, id):

    broken_values = ["", None, 0]
    
    composition = Composition.objects.get(id=id)

    comp_data_dict_list = list(Composition.objects.filter(id=id).values()) # could do all of this the Django way...
    comp_data_dict = comp_data_dict_list[0]


    # Chord 1
    chord1_tonic = comp_data_dict["chord1_tonic"]
    chord1_tonic_display = chord1_tonic
    if chord1_tonic_display == "A#":
        chord1_tonic_display = "A#/Bb"
    if chord1_tonic_display == "C#":
        chord1_tonic_display = "C#/Db"
    if chord1_tonic_display == "D#":
        chord1_tonic_display = "D#/Eb"
    if chord1_tonic_display == "F#":
        chord1_tonic_display = "F#/Gb"
    if chord1_tonic_display == "G#":
        chord1_tonic_display = "G#/Ab"

    chord1_quality = comp_data_dict["chord1_quality"]
    chord1_quality_display = chord1_quality
    if chord1_quality == None:
        chord1_quality_display = ""


    chord1_bars = comp_data_dict["chord1_bars"]
    chord1_bars_u = "bar(s)"
    if chord1_bars == 0:
        chord1_bars = ""
        chord1_bars_u = ""
    chord1_dg = [chord1_tonic, chord1_quality, chord1_bars]
    chord1_vis = False
    
    chord1_works = True
    chord1_vals = [chord1_tonic, chord1_quality, chord1_bars]
    for broken_value in broken_values:
        if broken_value in chord1_vals:
            chord1_works = False

    
    # Chord 2
    chord2_tonic = comp_data_dict["chord2_tonic"]
    chord2_tonic_display = chord2_tonic
    if chord2_tonic_display == "A#":
        chord2_tonic_display = "A#/Bb"
    if chord2_tonic_display == "C#":
        chord2_tonic_display = "C#/Db"
    if chord2_tonic_display == "D#":
        chord2_tonic_display = "D#/Eb"
    if chord2_tonic_display == "F#":
        chord2_tonic_display = "F#/Gb"
    if chord2_tonic_display == "G#":
        chord2_tonic_display = "G#/Ab"




    chord2_quality = comp_data_dict["chord2_quality"]
    chord2_quality_display = chord2_quality
    if chord2_quality == None:
        chord2_quality_display = ""
    
    
    chord2_bars = comp_data_dict["chord2_bars"]
    chord2_bars_u = "bar(s)"
    if chord2_bars == 0:
        chord2_bars = ""
        chord2_bars_u = ""
    chord2_dg = [chord2_tonic, chord2_quality, chord2_bars]
    chord2_vis = False
    chord2_works = True
    chord2_vals = [chord2_tonic, chord2_quality, chord2_bars]
    for broken_value in broken_values:
        if broken_value in chord2_vals:
            chord2_works = False

    # Chord 3
    chord3_tonic = comp_data_dict["chord3_tonic"]
    chord3_tonic_display = chord3_tonic
    if chord3_tonic_display == "A#":
        chord3_tonic_display = "A#/Bb"
    if chord3_tonic_display == "C#":
        chord3_tonic_display = "C#/Db"
    if chord3_tonic_display == "D#":
        chord3_tonic_display = "D#/Eb"
    if chord3_tonic_display == "F#":
        chord3_tonic_display = "F#/Gb"
    if chord3_tonic_display == "G#":
        chord3_tonic_display = "G#/Ab"


    chord3_quality = comp_data_dict["chord3_quality"]
    chord3_quality_display = chord3_quality
    if chord3_quality == None:
        chord3_quality_display = ""

    chord3_bars = comp_data_dict["chord3_bars"]
    chord3_bars_u = "bar(s)"
    if chord3_bars == 0:
        chord3_bars = ""
        chord3_bars_u = ""
    chord3_dg = [chord3_tonic, chord3_quality, chord3_bars]
    chord3_vis = False
    chord3_works = True
    chord3_vals = [chord3_tonic, chord3_quality, chord3_bars]
    for broken_value in broken_values:
        if broken_value in chord3_vals:
            chord3_works = False

    # Chord 4
    chord4_tonic = comp_data_dict["chord4_tonic"]
    chord4_tonic_display = chord4_tonic
    if chord4_tonic_display == "A#":
        chord4_tonic_display = "A#/Bb"
    if chord4_tonic_display == "C#":
        chord4_tonic_display = "C#/Db"
    if chord4_tonic_display == "D#":
        chord4_tonic_display = "D#/Eb"
    if chord4_tonic_display == "F#":
        chord4_tonic_display = "F#/Gb"
    if chord4_tonic_display == "G#":
        chord4_tonic_display = "G#/Ab"

    chord4_quality = comp_data_dict["chord4_quality"]
    chord4_quality_display = chord4_quality
    if chord4_quality == None:
        chord4_quality_display = ""


    chord4_bars = comp_data_dict["chord4_bars"]
    chord4_bars_u = "bar(s)"
    if chord4_bars == 0:
        chord4_bars = ""
        chord4_bars_u = ""
    chord4_dg = [chord4_tonic, chord4_quality, chord4_bars]
    chord4_vis = False
    chord4_works = True
    chord4_vals = [chord4_tonic, chord4_quality, chord4_bars]
    for broken_value in broken_values:
        if broken_value in chord4_vals:
            chord4_works = False

    # Chord 5
    chord5_tonic = comp_data_dict["chord5_tonic"]
    chord5_tonic_display = chord5_tonic
    if chord5_tonic_display == "A#":
        chord5_tonic_display = "A#/Bb"
    if chord5_tonic_display == "C#":
        chord5_tonic_display = "C#/Db"
    if chord5_tonic_display == "D#":
        chord5_tonic_display = "D#/Eb"
    if chord5_tonic_display == "F#":
        chord5_tonic_display = "F#/Gb"
    if chord5_tonic_display == "G#":
        chord5_tonic_display = "G#/Ab"


    chord5_quality = comp_data_dict["chord5_quality"]
    chord5_quality_display = chord5_quality
    if chord5_quality == None:
        chord5_quality_display = ""


    chord5_bars = comp_data_dict["chord5_bars"]
    chord5_bars_u = "bar(s)"
    if chord5_bars == 0:
        chord5_bars = ""
        chord5_bars_u = ""
    chord5_dg = [chord5_tonic, chord5_quality, chord5_bars]
    chord5_vis = False

userinput/templates/userinput/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Salieri | About </title>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
    <script src="https://unpkg.com/vue@3"></script>
    {% load static %}

    <style>
      label {color: #E2D8CC}
      small {color: #E2D8CC}
      a {color: #E2D8CC}
      nav {background-color: #130B23; }
      select {background-color: #E2D8CC; color: #130B23}
      input {background-color: #E2D8CC; color: #130B23;}
      body {background-image: linear-gradient(#0F0B26, #8C2641);}
      button {background-color: #0D0D0D
        ; border-color: #E2D8CC}
      #submit {background-color:#8C2641; border-color: #E2D8CC
      }
      #miniheadline {color: #E2D8CC}
      #sig {color: #E2D8CC}
      #miniheadline1 {color:#E0AB79
      }
      #miniheadline2 {color:#E2D8CC}
      #miniheadline3 {color:#E2D8CC}
      #textcontainer {background-color: #130B23
        ; border-color: #E2D8CC; color:#E2D8CC}
      #datacontainer {background-color: #130B23

        ; border-color: #E2D8CC}
      #datap {background-color: #E2D8CC; color: #130B23 }
      #dataheadings {color:#8C2641
      }
      #styleupdate{color:#22731D}
      #currchord{color:#22731D}

    </style>
</head>
<body style="min-height:100vh">
    
    <div id = "sal image div" class="mt5 tc">
        <a href="{% url 'userinput:index' %}"><img
            src="{% static 'userinput/coolsal.png' %}"
            class="br4 h5 w5 ba bw2 dib" alt="Salieri"
            style = "border-color: #E0AB79">
        </a>
    </div>

    <header class="tc pv4 calisto" style="color: #E2D8CC">
        <h1 class="mt2 mb0 calisto ttu tracked fw1 f-subheadline">Salieri</h1>
        <h2 class="mt2 f3 fw1 calisto i">you don't have to be mozart </h2>
        <nav class=" bt bb bw1 tc mw7 center mt4" style = "border-color: #E0AB79">
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:index' %}">Home</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:about' %}">About</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:instructions' %}">Instructions</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:dedication' %}">Dedication</a>
        </nav>
    </header>

    <main>
        <div id = "containersdiv" class = "flex flex-wrap justify-center h-100">
            <div id = "textcontainer" class = "pa4 mb3 arial ba bw2 h-100 br4" style = "border-color: #E2D8CC;">
                <div class = "measure">
                    
                    <div class = "f3 ">
                        <div class = "f2 flex justify-center">
                            <span id = "miniheadline1" class = "calisto"> What is Salieri? </span> <br>
                        </div>
                        <br>
                        Salieri is a music composition tool that allows users to create their own customizable music clips as downloadable MIDI.  
                        You don't need to play an instrument or read traditional notation, and there's no fee. <br><br> 
                        
                        (It does help to know some basic music terminology.  But my hope is to keep the knowledge barrier as low as possible, and there's no harm in experimenting even if you've never played a note in your life.) <br><br>
                        
                        Salieri is in very early development.  The present version is a demo that was thrown together in about a month as a project for PDX Code Guild.  It is my first fullstack web app, utilizing home-brewed python algorithms on the backend to generate the musical figures.  <br><br>
                        
                        Right now, Salieri's functionality is limited, but it is capable of writing simple accompaniment and complex, customizable arpeggios.  Already the app is a useful tool for creating your own jam session MIDI, or for creating musical setpieces you can import and manipulate in popular programs like Ableton.<br><br>
                        
                        In time, I am planning on drastically expanding the range and sophistication of Salieri's music writing algorithms.  Check back over time to see the project grow.<br><br>
                        
                        You can find the code for Salieri in my Github repository (link below).  Feel free to contact me if you're curious about the project or looking to collaborate.<br><br>
                        
                        <a id="miniheadline1" href="https://github.com/logandouglass/pdxcapstone">github.com/logandouglass/pdxcapstone</a><br><br>
                        <span id = "miniheadline1"> logandouglass@gmail.com </span>
                        <br><br>
                        
                            <span id = "" class = ""> - Logan </span> <br>



                    </div>
                </div>
            </div>
        </div>

    </main>


    <footer>
        <h4 id = "sig" class = "calisto f5 mb4 tc" > Logan Douglass | © 2022 </h4>
    </footer>

</body>
</html>

userinput/templates/userinput/aboutold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Salieri | About </title>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
    <script src="https://unpkg.com/vue@3"></script>
    {% load static %}

    <style>
      label {color: #E2D8CC}
      small {color: #E2D8CC}
      a {color: #E2D8CC}
      nav {background-color: #130B23; }
      select {background-color: #E2D8CC; color: #130B23}
      input {background-color: #E2D8CC; color: #130B23;}
      body {background-image: linear-gradient(#0F0B26, #8C2641);}
      button {background-color: #0D0D0D
        ; border-color: #E2D8CC}
      #submit {background-color:#8C2641; border-color: #E2D8CC
      }
      #miniheadline {color: #E2D8CC}
      #sig {color: #E2D8CC}
      #miniheadline1 {color:#E0AB79
      }
      #miniheadline2 {color:#E2D8CC}
      #miniheadline3 {color:#E2D8CC}
      #textcontainer {background-color: #130B23
        ; border-color: #E2D8CC; color:#E2D8CC}
      #datacontainer {background-color: #130B23

        ; border-color: #E2D8CC}
      #datap {background-color: #E2D8CC; color: #130B23 }
      #dataheadings {color:#8C2641
      }
      #styleupdate{color:#22731D}
      #currchord{color:#22731D}

    </style>
</head>
<body style="min-height:100vh">
    
    <div id = "sal image div" class="mt5 tc">
        <a href="{% url 'userinput:index' %}"><img
            src="{% static 'userinput/coolsal.png' %}"
            class="br4 h5 w5 ba bw2 dib" alt="Salieri"
            style = "border-color: #E0AB79">
        </a>
    </div>

    <header class="tc pv4 calisto" style="color: #E2D8CC">
        <h1 class="mt2 mb0 calisto ttu tracked fw1 f-subheadline">Salieri</h1>
        <h2 class="mt2 f3 fw1 calisto i">you don't have to be mozart </h2>
        <nav class=" bt bb bw1 tc mw7 center mt4" style = "border-color: #E0AB79">
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:index' %}">Home</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:about' %}">About</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:instructions' %}">Instructions</a>
          <a class="f4 f4-l link bg-animate dib pa3 ph4-l" href="{% url 'userinput:dedication' %}">Dedication</a>
        </nav>
    </header>

    <main>
        <div id = "containersdiv" class = "flex flex-wrap justify-center h-100">
            <div id = "textcontainer" class = "pa4 mb3 arial ba bw2 h-100 br4" style = "border-color: #E2D8CC;">
                <div class = "measure">
                    
                    <div class = "f3 ">
                        <div class = "f2 flex justify-center">
                            <span id = "miniheadline1" class = "calisto"> What is Salieri? </span> <br>
                        </div>
                        <br>
                        <p>
                        Salieri is a music composition tool that allows users to create their own customizable music clips as downloadable MIDI.  
                        You don't need to play an instrument or read traditional notation, and there's no fee. <br><br> 
                        
                        (It does help to know some basic music terminology.  But my hope is to keep the knowledge barrier as low as possible, and there's no harm in experimenting even if you've never played a note in your life.) <br><br>
                        
                        Salieri is in very early development.  The present version is a demo that was thrown together in about a month as a project for PDX Code Guild.  It is my first fullstack web app, utilizing home-brewed python algorithms on the backend to generate the musical figures.  <br><br>
                        
                        Right now, Salieri's functionality is limited, but it is capable of writing simple accompaniment and complex, customizable arpeggios.  Already the app is a useful tool for creating your own jam session MIDI, or for creating musical setpieces you can import and manipulate in popular programs like Ableton.<br><br>
                        
                        In time, I am planning on drastically expanding the range and sophistication of Salieri's music writing algorithms.  Check back over time to see the project grow.<br><br>
                        
                        You can find the code for Salieri in my Github repository (link below).  Feel free to contact me if you're curious about the project or looking to collaborate.<br><br>
                        </p>
                        <a id="miniheadline1" href="https://github.com/logandouglass/pdxcapstone">github.com/logandouglass/pdxcapstone</a><br><br>
                        <span id = "miniheadline1"> logandouglass@gmail.com </span>
                        <br><br>
                        
                            <span id = "" class = ""> - Logan </span> <br>



                    </div>
                </div>
            </div>
        </div>

    </main>


    <footer>
        <h4 id = "sig" class = "calisto f5 mb4 tc" > Logan Douglass | © 2022 </h4>
    </footer>

</body>
</html>